language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: hiredis
      latex: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - libapparmor-dev
      - libhiredis-dev
      - redis-server

services:
  - redis-server

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr

r_github_packages:
  - richfitz/storr@develop

after_success:
  - Rscript -e 'covr::codecov()'
