language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libhiredis-dev
      - redis-server

services:
  - redis-server

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
